title: LIMRI
description: London Interdisciplinary Music Research Initiative
github_username: dmrn-limri
url: "https://dmrn-limri.github.io"
baseurl: ""

permalink: /:slug.html

# Build settings
remote_theme: riggraz/no-style-please
# markdown: kramdown

# Show posts with dates in the future
future: true

# Optional: customize theme settings
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "← back" # customize text for homepage link in post layout
  date_format: "%Y-%m" # customize how dates are displayed
  show_description: true # show tagline under title
  lowercase_titles: false

# Uncomment if you want to add navigation menu
# menu:
#   - title: about
#     entries:
#       - title: LIMRI
#         url: /about
#   - title: research
#     entries:
#       - title: projects
#         url: /research/projects
#   - title: contact
#     url: /contact

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - README.md
